---
services:
  postgresdb:
    image: postgres:16.4
    restart: always
    hostname: postgresdb
    container_name: postgresdb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - postgres-network


  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin4-server
    hostname: pgadmin
    depends_on:
      - postgresdb
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
       PGADMIN_DEFAULT_PASSWORD: "password"
       PGADMIN_CONFIG_SERVER_MODE: 'False'
       PGADMIN_LISTEN_PORT: 80
    ports:
      - '16543:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  db:
    driver: local
  pgadmin-data:
